<a href="https://colab.research.google.com/github/trevinofernando/AI-MachineLearning/blob/master/hw2/Width_Height_Extraction_Logic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#a = np.array(range(9)).reshape((3,3))
a = np.array([[
                [0,  0,  0, 0],
                [0, .2, .5, 0],
                [0, .7, .8, 0],
                [0,  0,  0, 0]
              ],
              [
                [0,  0,  0, 0],
                [0, .1, .3, 0],
                [0, .4, .6, 0],
                [0,  0, .9, 0]]])
imgCount, col, rows = a.shape
a.shape

(2, 4, 4)

In [2]:
# Get the maximum values of each column
maxInColumns = np.amax(a, axis=1)
print(maxInColumns)
print("")
# Get the maximum values of each row
maxInRows = np.amax(a, axis=2)
print(maxInRows)

[[0.  0.7 0.8 0. ]
 [0.  0.4 0.9 0. ]]

[[0.  0.5 0.8 0. ]
 [0.  0.3 0.6 0.9]]


In [3]:
#(xLimits, yLimits)= np.where(a > 0)
#print(xLimits, yLimits)
(x, y, z)= np.where(a > 0)
print(x)
print(y)
print(z)

indices = np.transpose(np.where(a > 0))
indices

[0 0 0 0 1 1 1 1 1]
[1 1 2 2 1 1 2 2 3]
[1 2 1 2 1 2 1 2 2]


array([[0, 1, 1],
       [0, 1, 2],
       [0, 2, 1],
       [0, 2, 2],
       [1, 1, 1],
       [1, 1, 2],
       [1, 2, 1],
       [1, 2, 2],
       [1, 3, 2]])

In [4]:
h = np.array([])
w = np.array([])
for i in range(imgCount):
  img = np.where(x == i)[0]
  print(img)
  h = np.concatenate((h, np.atleast_1d(y[img[-1]] - y[img[0]] + 1)), axis = 0)
  w = np.concatenate((w, np.atleast_1d(z[img[-1]] - z[img[0]] + 1)), axis = 0)
  print(h)
  print(w)
  print(h.shape)

[0 1 2 3]
[2.]
[2.]
(1,)
[4 5 6 7 8]
[2. 3.]
[2. 2.]
(2,)


In [5]:
h = np.array([])
w = np.array([])
for i in range(imgCount):
  img = np.where(x == i)[0]
  print(img)
  h = np.append(h, y[img[-1]] - y[img[0]] + 1)
  w = np.append(w, z[img[-1]] - z[img[0]] + 1)
  print(h)
  print(w)
  print(h.shape)
h = h.reshape(imgCount, 1)
w = w.reshape(imgCount, 1)
print(h)
print(w)

[0 1 2 3]
[2.]
[2.]
(1,)
[4 5 6 7 8]
[2. 3.]
[2. 2.]
(2,)
[[2.]
 [3.]]
[[2.]
 [2.]]
